import 'package:flutter/material.dart';

class AppColors {
  static const Color primaryGreen = Color(0xFF2E7D32);
  static const Color secondaryGreen = Color(0xFF4CAF50);
  static const Color lightGreen = Color(0xFF81C784);
  static const Color darkGreen = Color(0xFF1B5E20);

  static const Color soilBrown = Color(0xFF795548);
  static const Color waterBlue = Color(0xFF2196F3);
  static const Color alertRed = Color(0xFFF44336);
  static const Color warningOrange = Color(0xFFFF9800);

  static const Color background = Color(0xFFF5F5F5);
  static const Color cardBackground = Colors.white;
  static const Color textPrimary = Color(0xFF212121);
  static const Color textSecondary = Color(0xFF757575);

  // Added for compatibility with existing code
  static const Color softCoral = Color(0xFFFFAB91);
  static const Color brightCyan = Color(0xFF80DEEA);
  static const Color emeraldGreen = Color(0xFFA5D6A7);
}

class AppConstants {
  static const String appName = 'KrishiMitra';
  static const String appTagline = 'Your Voice-Enabled AI Farm Companion';

  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'hi': 'हिंदी',
    'bn': 'বাংলা',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'mr': 'मराठी',
    'gu': 'ગુજરાતી',
    'kn': 'ಕನ್ನಡ',
    'ml': 'മലയാളം',
    'pa': 'ਪੰਜਾਬੀ',
  };

  static const List<Map<String, dynamic>> dashboardModules = [
    {
      'id': 'voice_camera',
      'title': 'Voice + Camera',
      'titleHi': 'आवाज़ + कैमरा',
      'icon': Icons.mic,
      'color': Color(0xFF4CAF50),
      'description': 'Ask about crops, get instant advice',
    },
    {
      'id': 'sensors',
      'title': 'Field Sensors',
      'titleHi': 'सेंसर डैशबोर्ड',
      'icon': Icons.sensors,
      'color': Color(0xFF2196F3),
      'description': 'Monitor soil, moisture & NPK',
    },
    {
      'id': 'market',
      'title': 'Market Prices',
      'titleHi': 'बाज़ार मूल्य',
      'icon': Icons.trending_up,
      'color': Color(0xFFFF9800),
      'description': 'Real-time mandi prices & trends',
    },
    {
      'id': 'weather',
      'title': 'Weather',
      'titleHi': 'मौसम',
      'icon': Icons.wb_sunny,
      'color': Color(0xFF00BCD4),
      'description': 'Seasonal intelligence & forecasts',
    },
    {
      'id': 'alerts',
      'title': 'Alerts',
      'titleHi': 'अलर्ट',
      'icon': Icons.warning,
      'color': Color(0xFFF44336),
      'description': 'Contamination & storm alerts',
    },
  ];
}

class AppStrings {
  static String get(String key, String lang) {
    return translations[lang]?[key] ?? translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'KrishiMitra',
      'greeting': 'Namaste! 🌱',
      'greeting_sub': 'How is your farm today?',
      'temp_label': 'Temperature',
      'moisture_label': 'Moisture',
      'crop_label': 'Crop',
      'voice_module': 'Voice + Camera',
      'sensor_module': 'Field Sensors',
      'market_module': 'Market Prices',
      'weather_module': 'Weather',
      'alerts_module': 'Alerts',
      'recent_alerts': '📊 Recent Alerts',
      'rain_warning_title': 'Rain Warning',
      'rain_warning_desc': 'Rain expected in next 3 hours',
      'wheat_sell_title': 'Wheat Sell Time',
      'wheat_sell_desc': 'Current prices are high',
      'market_title': 'Market Prices',
      'weather_title': 'Weather Forecast',
      'sensor_title': 'Field Sensors',
      'alerts_title': 'Alerts & Warnings',
      'home': 'Home',
      'voice': 'Voice',
      'market': 'Market',
      'weather': 'Weather',
      'selling_tip': 'Selling Tip',
      'forecast': 'Price Forecast',
      'nearby_mandis': 'Nearby Mandi Prices',
      'trend': 'Price Trend',
      'disclaimer_title': 'Prototype / Demo Mode',
      'disclaimer_msg': 'Note: AI Voice Assistant is not deployed to a live cloud backend. This is an interactive static prototype and UI simulation for demonstration.',
      'Wheat': 'Wheat',
      'Rice': 'Rice',
      'Maize': 'Maize',
      'Soybean': 'Soybean',
      'Cotton': 'Cotton',
      'Mustard': 'Mustard',
      'Potato': 'Potato',
    },
    'hi': {
      'app_name': 'कृषि मित्र',
      'greeting': 'नमस्ते! 🌱',
      'greeting_sub': 'आज आपका खेत कैसा है?',
      'temp_label': 'तापमान',
      'moisture_label': 'नमी',
      'crop_label': 'फसल',
      'voice_module': 'आवाज़ + कैमरा',
      'sensor_module': 'सेंसर डैशबोर्ड',
      'market_module': 'बाज़ार मूल्य',
      'weather_module': 'मौसम',
      'alerts_module': 'अलर्ट',
      'recent_alerts': '📊 नवीनतम अलर्ट',
      'rain_warning_title': 'बारिश की चेतावनी',
      'rain_warning_desc': 'अगले 3 घंटे में बारिश की संभावना',
      'wheat_sell_title': 'गेहूं बेचने का समय',
      'wheat_sell_desc': 'कीमत अभी ऊँची है',
      'market_title': 'बाज़ार मूल्य (मंडी भाव)',
      'weather_title': 'मौसम पूर्वानुमान',
      'sensor_title': 'खेत सेंसर',
      'alerts_title': 'अलर्ट और चेतावनी',
      'home': 'मुख्य',
      'voice': 'आवाज़',
      'market': 'बाज़ार',
      'weather': 'मौसम',
      'selling_tip': 'बेचने का सुझाव',
      'forecast': 'मूल्य पूर्वानुमान',
      'nearby_mandis': 'आस-पास के मंडी भाव',
      'trend': 'मूल्य रुझान',
      'disclaimer_title': 'प्रोटोटाइप / डेमो मोड',
      'disclaimer_msg': 'नोट: एआई वॉयस असिस्टेंट लाइव बैकएंड पर तैनात नहीं है। यह प्रदर्शन के लिए एक स्थिर प्रोटोटाइप और यूआई सिमुलेशन है।',
      'Wheat': 'गेहूं',
      'Rice': 'चावल (धान)',
      'Maize': 'मक्का',
      'Soybean': 'सोयाबीन',
      'Cotton': 'कपास',
      'Mustard': 'सरसों',
      'Potato': 'आलू',
    },
    'mr': {
      'app_name': 'कृषी मित्र',
      'greeting': 'नमस्कार! 🌱',
      'greeting_sub': 'आज तुमचे शेत कसे आहे?',
      'temp_label': 'तापमान',
      'moisture_label': 'ओलावा',
      'crop_label': 'पीक',
      'voice_module': 'आवाज + कॅमेरा',
      'sensor_module': 'सेंसर डॅशबोर्ड',
      'market_module': 'बाजार भाव',
      'weather_module': 'हवामान',
      'alerts_module': 'सूचना',
      'recent_alerts': '📊 नवीनतम सूचना',
      'rain_warning_title': 'पावसाचा इशारा',
      'rain_warning_desc': 'पुढील ३ तासांत पावसाची शक्यता',
      'wheat_sell_title': 'गहू विक्रीची वेळ',
      'wheat_sell_desc': 'सध्याचे भाव चढे आहेत',
      'market_title': 'बाजार भाव',
      'weather_title': 'हवामान अंदाज',
      'sensor_title': 'शेत सेन्सर',
      'alerts_title': 'सूचना व चेतावणी',
      'home': 'मुख्य',
      'voice': 'आवाज',
      'market': 'बाजार',
      'weather': 'हवामान',
      'selling_tip': 'विक्री सल्ला',
      'forecast': 'भाव अंदाज',
      'nearby_mandis': 'जवळपासचे बाजार भाव',
      'trend': 'भाव कल',
      'disclaimer_title': 'प्रोटोटाइप / डेमो मोड',
      'disclaimer_msg': 'टीप: एआय व्हॉईस असिस्टंट थेट तैनात नाही. हे प्रात्यक्षिकासाठी एक स्थिर प्रोटोटाइप आहे.',
      'Wheat': 'गहू',
      'Rice': 'भात',
      'Maize': 'मका',
      'Soybean': 'सोयाबीन',
      'Cotton': 'कापूस',
      'Mustard': 'मोहरी',
      'Potato': 'बटाटा',
    },
    'bn': {
      'app_name': 'কৃষি মিত্র',
      'greeting': 'নমস্কার! 🌱',
      'greeting_sub': 'আজ আপনার খামার কেমন আছে?',
      'temp_label': 'তাপমাত্রা',
      'moisture_label': 'আর্দ্রতা',
      'crop_label': 'ফসল',
      'voice_module': 'ভয়েস + ক্যামেরা',
      'sensor_module': 'সেন্সর ড্যাশবোর্ড',
      'market_module': 'বাজার দর',
      'weather_module': 'আবহাওয়া',
      'alerts_module': 'সতর্কতা',
      'recent_alerts': '📊 সাম্প্রতিক সতর্কতা',
      'rain_warning_title': 'বৃষ্টির সতর্কতা',
      'rain_warning_desc': 'পরবর্তী ৩ ঘণ্টার মধ্যে বৃষ্টির সম্ভাবনা',
      'wheat_sell_title': 'গম বিক্রির সময়',
      'wheat_sell_desc': 'বর্তমান দাম বেশ ভালো',
      'market_title': 'বাজারের দাম',
      'weather_title': 'আবহাওয়ার পূর্বাভাস',
      'sensor_title': 'খামার সেন্সর',
      'alerts_title': 'সতর্কতা ও পূর্বাভাস',
      'home': 'হোম',
      'voice': 'ভয়েস',
      'market': 'বাজার',
      'weather': 'আবহাওয়া',
      'selling_tip': 'বিক্রয় পরামর্শ',
      'forecast': 'দামের পূর্বাভাস',
      'nearby_mandis': 'কাছের বাজারের দর',
      'trend': 'দামের গতিপ্রকৃতি',
      'disclaimer_title': 'প্রোটোটাইপ মোড',
      'disclaimer_msg': 'নোট: ভয়েস সহকারী বর্তমানে প্রদর্শনের জন্য একটি স্ট্যাটিক প্রোটোটাইপ।',
      'Wheat': 'গম',
      'Rice': 'ধান / চাল',
      'Maize': 'ভুট্টা',
      'Soybean': 'সয়াবিন',
      'Cotton': 'তুলা',
      'Mustard': 'সরিষা',
      'Potato': 'আলু',
    },
    'te': {
      'app_name': 'కృషి మిత్ర',
      'greeting': 'నమస్కారం! 🌱',
      'greeting_sub': 'ఈరోజు మీ పొలం ఎలా ఉంది?',
      'temp_label': 'ఉష్ణోగ్రత',
      'moisture_label': 'తేమ',
      'crop_label': 'పంట',
      'voice_module': 'వాయిస్ + కెమెరా',
      'sensor_module': 'సెన్సార్ డాష్బోర్డ్',
      'market_module': 'మార్కెట్ ధరలు',
      'weather_module': 'వాతావరణం',
      'alerts_module': 'హెచ్చరికలు',
      'recent_alerts': '📊 ఇటీవలి హెచ్చరికలు',
      'rain_warning_title': 'వర్ష సూచన',
      'rain_warning_desc': 'రాబోయే 3 గంటల్లో వర్షం కురిసే అవకాశం',
      'wheat_sell_title': 'గోధుమ అమ్మకపు సమయం',
      'wheat_sell_desc': 'ప్రస్తుత ధరలు ఎక్కువగా ఉన్నాయి',
      'market_title': 'మార్కెట్ ధరలు',
      'weather_title': 'వాతావరణ సూచన',
      'sensor_title': 'పొలం సెన్సార్లు',
      'alerts_title': 'హెచ్చరికలు',
      'home': 'హోమ్',
      'voice': 'వాయిస్',
      'market': 'మార్కెట్',
      'weather': 'వాతావరణం',
      'selling_tip': 'అమ్మకపు సలహా',
      'forecast': 'ధరల అంచనా',
      'nearby_mandis': 'సమీప మార్కెట్ ధరలు',
      'trend': 'ధరల సరళి',
      'disclaimer_title': 'ప్రోటోటైప్ మోడ్',
      'disclaimer_msg': 'గమనిక: AI వాయిస్ అసిస్టెంట్ డెమో ప్రదర్శన కోసం రూపొందించబడింది.',
      'Wheat': 'గోధుమలు',
      'Rice': 'వరి / బియ్యం',
      'Maize': 'మొక్కజొన్న',
      'Soybean': 'సోయాబీన్',
      'Cotton': 'పత్తి',
      'Mustard': 'ఆవాలు',
      'Potato': 'బంగాళాదుంప',
    },
    'ta': {
      'app_name': 'கிஷி மித்ரா',
      'greeting': 'வணக்கம்! 🌱',
      'greeting_sub': 'இன்று உங்கள் பண்ணை எப்படி உள்ளது?',
      'temp_label': 'வெப்பநிலை',
      'moisture_label': 'ஈரப்பதம்',
      'crop_label': 'பயிர்',
      'voice_module': 'குரல் + கேமரா',
      'sensor_module': 'சென்சார் பலகை',
      'market_module': 'சந்தை விலை',
      'weather_module': 'வானிலை',
      'alerts_module': 'எச்சரிக்கைகள்',
      'recent_alerts': '📊 சமீபத்திய எச்சரிக்கைகள்',
      'rain_warning_title': 'மழை எச்சரிக்கை',
      'rain_warning_desc': 'அடுத்த 3 மணி நேரத்தில் மழை எதிர்பார்க்கப்படுகிறது',
      'wheat_sell_title': 'கோதுமை விற்பனை நேரம்',
      'wheat_sell_desc': 'தற்போதைய விலை அதிகமாக உள்ளது',
      'market_title': 'சந்தை விலைகள்',
      'weather_title': 'வானிலை அறிக்கை',
      'sensor_title': 'பண்ணை சென்சார்கள்',
      'alerts_title': 'எச்சரிக்கைகள்',
      'home': 'முகப்பு',
      'voice': 'குரல்',
      'market': 'சந்தை',
      'weather': 'வானிலை',
      'selling_tip': 'விற்பனை குறிப்பு',
      'forecast': 'விலை கணிப்பு',
      'nearby_mandis': 'அருகிலுள்ள சந்தை விலைகள்',
      'trend': 'விலை போக்கு',
      'disclaimer_title': 'மாதிரி வடிவம்',
      'disclaimer_msg': 'குறிப்பு: AI குரல் உதவியாளர் மாதிரி விளக்கத்திற்காக மட்டுமே.',
      'Wheat': 'கோதுமை',
      'Rice': 'நெல் / அரிசி',
      'Maize': 'சோளம்',
      'Soybean': 'சோயாபீன்',
      'Cotton': 'பருத்தி',
      'Mustard': 'கடுகு',
      'Potato': 'உருளைக்கிழங்கு',
    },
    'gu': {
      'app_name': 'કૃષિ મિત્ર',
      'greeting': 'નમસ્તે! 🌱',
      'greeting_sub': 'આજે તમારું ખેતર કેવું છે?',
      'temp_label': 'તાપમાન',
      'moisture_label': 'ભેજ',
      'crop_label': 'પાક',
      'voice_module': 'અવાજ + કૅમેરા',
      'sensor_module': 'સેન્સર ડેશબોર્ડ',
      'market_module': 'બજાર ભાવ',
      'weather_module': 'હવામાન',
      'alerts_module': 'ચેતવણીઓ',
      'recent_alerts': '📊 તાજેતરની ચેતવણીઓ',
      'rain_warning_title': 'વરસાદની ચેતવણી',
      'rain_warning_desc': 'આગામી 3 કલાકમાં વરસાદની સંભાવના',
      'wheat_sell_title': 'ઘઉં વેચવાનો સમય',
      'wheat_sell_desc': 'હાલમાં ભાવો ઊંચા છે',
      'market_title': 'મંડી ભાવો',
      'weather_title': 'હવામાન આગાહી',
      'sensor_title': 'ખેતર સેન્સર',
      'alerts_title': 'ચેતવણીઓ',
      'home': 'હોમ',
      'voice': 'અવાજ',
      'market': 'બજાર',
      'weather': 'હવામાન',
      'selling_tip': 'વેચાણ સલાહ',
      'forecast': 'ભાવ આગાહી',
      'nearby_mandis': 'નજીકના મંડી ભાવો',
      'trend': 'ભાવ વલણ',
      'disclaimer_title': 'પ્રોટોટાઇપ મોડ',
      'disclaimer_msg': 'નોંધ: AI વૉઇસ સહાયક ડેમો પ્રદર્શન માટે છે.',
      'Wheat': 'ઘઉં',
      'Rice': 'ડાંગર / ચોખા',
      'Maize': 'મકાઈ',
      'Soybean': 'સોયાબીન',
      'Cotton': 'કપાસ',
      'Mustard': 'સરસવ',
      'Potato': 'બટાટા',
    },
    'kn': {
      'app_name': 'ಕೃಷಿ ಮಿತ್ರ',
      'greeting': 'ನಮಸ್ಕಾರ! 🌱',
      'greeting_sub': 'ಇಂದು ನಿಮ್ಮ ಜಮೀನು ಹೇಗಿದೆ?',
      'temp_label': 'ತಾಪಮಾನ',
      'moisture_label': 'ತೇವಾಂಶ',
      'crop_label': 'ಬೆಳೆ',
      'voice_module': 'ಧ್ವನಿ + ಕ್ಯಾಮೆರಾ',
      'sensor_module': 'ಸೆನ್ಸಾರ್ ಡ್ಯಾಶ್ಬೋರ್ಡ್',
      'market_module': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
      'weather_module': 'ಹವಾಮಾನ',
      'alerts_module': 'ಎಚ್ಚರಿಕೆಗಳು',
      'recent_alerts': '📊 ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು',
      'rain_warning_title': 'ಮಳೆ ಎಚ್ಚರಿಕೆ',
      'rain_warning_desc': 'ಮುಂದಿನ 3 ಗಂಟೆಗಳಲ್ಲಿ ಮಳೆಯಾಗುವ ಸಾಧ್ಯತೆ',
      'wheat_sell_title': 'ಗೋಧಿ ಮಾರಾಟ ಸಮಯ',
      'wheat_sell_desc': 'ಪ್ರಸ್ತುತ ಬೆಲೆಗಳು ಹೆಚ್ಚಿವೆ',
      'market_title': 'ಮಾರುಕಟ್ಟೆ ದರಗಳು',
      'weather_title': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
      'sensor_title': 'ಕ್ಷೇತ್ರ ಸೆನ್ಸಾರ್',
      'alerts_title': 'ಎಚ್ಚರಿಕೆಗಳು',
      'home': 'ಮುಖಪುಟ',
      'voice': 'ಧ್ವನಿ',
      'market': 'ಮಾರುಕಟ್ಟೆ',
      'weather': 'ಹವಾಮಾನ',
      'selling_tip': 'ಮಾರಾಟ ಸಲಹೆ',
      'forecast': 'ಬೆಲೆ ಮುನ್ಸೂಚನೆ',
      'nearby_mandis': 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
      'trend': 'ಬೆಲೆ ಪ್ರವೃತ್ತಿ',
      'disclaimer_title': 'ಮಾದರಿ ಮೋಡ್',
      'disclaimer_msg': 'ಸೂಚನೆ: AI ಧ್ವನಿ ಸಹಾಯಕ ಡೆಮೊ ಪ್ರದರ್ಶನಕ್ಕಾಗಿ ಮಾತ್ರ.',
      'Wheat': 'ಗೋಧಿ',
      'Rice': 'ಭತ್ತ / ಅಕ್ಕಿ',
      'Maize': 'ಮೆಕ್ಕೆಜೋಳ',
      'Soybean': 'ಸೋಯಾಬೀನ್',
      'Cotton': 'ಹತ್ತಿ',
      'Mustard': 'ಸಾಸಿವೆ',
      'Potato': 'ಆಲೂಗಡ್ಡೆ',
    },
    'ml': {
      'app_name': 'കൃഷി മിത്ര',
      'greeting': 'നമസ്കാരം! 🌱',
      'greeting_sub': 'ഇന്ന് നിങ്ങളുടെ കൃഷിസ്ഥലം എങ്ങനെയുണ്ട്?',
      'temp_label': 'താപനില',
      'moisture_label': 'ഈർപ്പം',
      'crop_label': 'വിള',
      'voice_module': 'ശബ്ദം + ക്യാമറ',
      'sensor_module': 'സെൻസർ ഡാഷ്ബോർഡ്',
      'market_module': 'വിപണി വില',
      'weather_module': 'കാലാവസ്ഥ',
      'alerts_module': 'മുന്നറിയിപ്പുകൾ',
      'recent_alerts': '📊 പുതിയ മുന്നറിയിപ്പുകൾ',
      'rain_warning_title': 'മഴ മുന്നറിയിപ്പ്',
      'rain_warning_desc': 'അടുത്ത 3 മണിക്കൂറിനുള്ളിൽ മഴയ്ക്ക് സാധ്യത',
      'wheat_sell_title': 'ഗോതമ്പ് വിൽപന സമയം',
      'wheat_sell_desc': 'നിലവിലെ വില ഉയർന്നതാണ്',
      'market_title': 'വിപണി നിരക്കുകൾ',
      'weather_title': 'കാലാവസ്ഥ പ്രവചനം',
      'sensor_title': 'വയൽ സെൻസറുകൾ',
      'alerts_title': 'മുന്നറിയിപ്പുകൾ',
      'home': 'ഹോം',
      'voice': 'ശബ്ദം',
      'market': 'വിപണി',
      'weather': 'കാലാവസ്ഥ',
      'selling_tip': 'വിൽപ്പന നിർദ്ദേശം',
      'forecast': 'വില പ്രവചനം',
      'nearby_mandis': 'സമീപ വിപണി വിലകൾ',
      'trend': 'വില പ്രവണത',
      'disclaimer_title': 'പ്രോട്ടോടൈപ്പ് മോഡ്',
      'disclaimer_msg': 'ശ്രദ്ധിക്കുക: AI വോയ്സ് അസിസ്റ്റന്റ് ഒരു ഡെമോ പ്രോട്ടോടൈപ്പാണ്.',
      'Wheat': 'ഗോതമ്പ്',
      'Rice': 'നെല്ല് / അരി',
      'Maize': 'ചോളം',
      'Soybean': 'സോയാബീൻ',
      'Cotton': 'പരുത്തി',
      'Mustard': 'കടുക്',
      'Potato': 'ഉരുളക്കിഴങ്ങ്',
    },
    'pa': {
      'app_name': 'ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ',
      'greeting': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! 🌱',
      'greeting_sub': 'ਅੱਜ ਤੁਹਾਡਾ ਖੇਤ ਕਿਵੇਂ ਹੈ?',
      'temp_label': 'ਤਾਪਮਾਨ',
      'moisture_label': 'ਨਮੀ',
      'crop_label': 'ਫ਼ਸਲ',
      'voice_module': 'ਆਵਾਜ਼ + ਕੈਮਰਾ',
      'sensor_module': 'ਸੈਂਸਰ ਡੈਸ਼ਬੋਰਡ',
      'market_module': 'ਮੰਡੀ ਭਾਅ',
      'weather_module': 'ਮੌਸਮ',
      'alerts_module': 'ਚੇਤਾਵਨੀਆਂ',
      'recent_alerts': '📊 ਤਾਜ਼ਾ ਚੇਤਾਵਨੀਆਂ',
      'rain_warning_title': 'ਮੀਂਹ ਦੀ ਚੇਤਾਵਨੀ',
      'rain_warning_desc': 'ਅਗਲੇ 3 ਘੰਟਿਆਂ ਵਿੱਚ ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ',
      'wheat_sell_title': 'ਕਣਕ ਵੇਚਣ ਦਾ ਸਮਾਂ',
      'wheat_sell_desc': 'ਮੌਜੂਦਾ ਭਾਅ ਚੰਗੇ ਹਨ',
      'market_title': 'ਮੰਡੀ ਦੇ ਭਾਅ',
      'weather_title': 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ',
      'sensor_title': 'ਖੇਤ ਸੈਂਸਰ',
      'alerts_title': 'ਚੇਤਾਵਨੀਆਂ',
      'home': 'ਮੁੱਖ',
      'voice': 'ਆਵਾਜ਼',
      'market': 'ਮੰਡੀ',
      'weather': 'ਮੌਸਮ',
      'selling_tip': 'ਵੇਚਣ ਦੀ ਸਲਾਹ',
      'forecast': 'ਭਾਅ ਭਵਿੱਖਬਾਣੀ',
      'nearby_mandis': 'ਨੇੜਲੀਆਂ ਮੰਡੀਆਂ ਦੇ ਭਾਅ',
      'trend': 'ਕੀਮਤ ਦਾ ਰੁਝਾਨ',
      'disclaimer_title': 'ਪ੍ਰੋਟੋਟਾਈਪ ਮੋਡ',
      'disclaimer_msg': 'ਨੋਟ: AI ਵੌਇਸ ਅਸਿਸਟੈਂਟ ਡੈਮੋ ਪ੍ਰਦਰਸ਼ਨ ਲਈ ਹੈ।',
      'Wheat': 'ਕਣਕ',
      'Rice': 'ਝੋਨਾ / ਚੌਲ',
      'Maize': 'ਮੱਕੀ',
      'Soybean': 'ਸੋਇਆਬੀਨ',
      'Cotton': 'ਕਪਾਹ',
      'Mustard': 'ਸਰ੍ਹੋਂ',
      'Potato': 'ਆਲੂ',
    },
  };
}
