import 'package:flutter/material.dart';

class AppColors {
  // Premium Enterprise AgriTech Palette
  static const Color primaryGreen = Color(0xFF0F5132); // Deep Luxury Emerald
  static const Color secondaryGreen = Color(0xFF198754);
  static const Color lightGreen = Color(0xFF86EFAC);
  static const Color darkGreen = Color(0xFF082F1D);
  static const Color emerald = Color(0xFF10B981);

  static const Color soilBrown = Color(0xFF78350F);
  static const Color waterBlue = Color(0xFF0284C7);
  static const Color skyBlue = Color(0xFF38BDF8);
  static const Color alertRed = Color(0xFFDC2626);
  static const Color warningOrange = Color(0xFFD97706);
  static const Color accentGold = Color(0xFFF59E0B);

  static const Color background = Color(0xFFF8FAFC); // Clean Slate
  static const Color surface = Color(0xFFF1F5F9);
  static const Color cardBackground = Colors.white;
  static const Color textPrimary = Color(0xFF0F172A); // High Contrast Slate
  static const Color textSecondary = Color(0xFF64748B);
  static const Color cardBorder = Color(0x1A0F5132);

  // Soft accents for metric badges
  static const Color softCoral = Color(0xFFFFE4E6);
  static const Color brightCyan = Color(0xFFE0F2FE);
  static const Color emeraldGreen = Color(0xFFDCFCE7);
}

class AppConstants {
  static const String appName = 'KrishiMitra';
  static const String appTagline = 'Your Voice-Enabled AI Farm Companion';

  static const Map<String, String> supportedLanguages = {
    'en': 'English',
    'hi': 'हिंदी',
    'mr': 'मराठी',
    'bn': 'বাংলা',
    'te': 'తెలుగు',
    'ta': 'தமிழ்',
    'gu': 'ગુજરાતી',
    'kn': 'ಕನ್ನಡ',
    'ml': 'മലയാളം',
    'pa': 'ਪੰਜਾਬੀ',
  };

  static const List<Map<String, dynamic>> dashboardModules = [
    {
      'id': 'voice_camera',
      'title': 'Voice + Camera',
      'titleHi': 'आवाज़ + कैमरा',
      'icon': Icons.mic_rounded,
      'color': Color(0xFF0F5132),
      'description': 'Ask about crops, get instant advice',
    },
    {
      'id': 'sensors',
      'title': 'Field Sensors',
      'titleHi': 'सेंसर डैशबोर्ड',
      'icon': Icons.sensors_rounded,
      'color': Color(0xFF0284C7),
      'description': 'Monitor soil, moisture & NPK',
    },
    {
      'id': 'market',
      'title': 'Market Prices',
      'titleHi': 'बाज़ार मूल्य',
      'icon': Icons.trending_up_rounded,
      'color': Color(0xFFD97706),
      'description': 'Real-time mandi prices & trends',
    },
    {
      'id': 'weather',
      'title': 'Weather Intel',
      'titleHi': 'मौसम',
      'icon': Icons.wb_sunny_rounded,
      'color': Color(0xFF0891B2),
      'description': 'Seasonal intelligence & forecasts',
    },
    {
      'id': 'alerts',
      'title': 'Alerts',
      'titleHi': 'अलर्ट',
      'icon': Icons.warning_amber_rounded,
      'color': Color(0xFFDC2626),
      'description': 'Contamination & storm alerts',
    },
  ];
}

class AppStrings {
  static String get(String key, String lang) {
    return translations[lang]?[key] ?? translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> translations = {
    'en': {
      'app_name': 'KrishiMitra',
      'greeting': 'Namaste! 🌱',
      'greeting_sub': 'How is your farm today?',
      'temp_label': 'Temperature',
      'moisture_label': 'Moisture',
      'crop_label': 'Primary Crop',
      'voice_module': 'Voice Assistant',
      'sensor_module': 'Field Sensors',
      'market_module': 'Market Prices',
      'weather_module': 'Weather Intel',
      'alerts_module': 'Smart Alerts',
      'recent_alerts': 'Recent Alerts',
      'rain_warning_title': 'Rain Warning',
      'rain_warning_desc': 'Rain expected in next 3 hours',
      'wheat_sell_title': 'Wheat Sell Time',
      'wheat_sell_desc': 'Current prices are high',
      'market_title': 'Market Prices (Mandi)',
      'weather_title': 'Weather Intelligence',
      'sensor_title': 'ESP32 Field Sensors',
      'read_out': 'Read Out',
      'stop': 'Stop',
      'read_ai_predictions': 'Read AI Predictions',
      'speak_sensor_data': 'Listen to Sensor Data',
      'alerts_title': 'Alerts & Warnings',
      'home': 'Home',
      'voice': 'Voice Assistant',
      'market': 'Market',
      'weather': 'Weather',
      'selling_tip': 'Selling Tip',
      'forecast': 'Price Forecast',
      'nearby_mandis': 'Nearby Mandi Prices',
      'trend': 'Price Trend',
      'daily_outlook': '7-Day Outlook',
      'nowcast_advisory': 'Nowcast & Radar Advisory',
      'season_advice': 'Seasonal Agronomy Advice',
      'recommended_crops': 'Recommended Crops',
      'humidity_label': 'Humidity',
      'wind_label': 'Wind',
      'rain_label': 'Rain',
      'sensor_connected': 'ESP32 Connected - Node #1',
      'sensor_disconnected': 'ESP32 Disconnected',
      'soil_moisture': 'Soil Moisture',
      'soil_ph': 'Soil pH',
      'npk_levels': 'NPK Nutrient Balance',
      'nitrogen': 'Nitrogen (N)',
      'phosphorus': 'Phosphorus (P)',
      'potassium': 'Potassium (K)',
      'moisture_trend': '24-Hour Moisture Trend',
      'smart_alerts_active': 'Smart Alerts Active',
      'smart_alerts_sub': '24/7 Monitoring: ESP32 + IMD Radar + CPCB Water Quality',
      'suggested_action': 'Suggested action',
      'got_it': 'Got it',
      'hear': 'Hear Audio',
      'sensors': 'Sensors',
      'nowcast': 'Nowcast',
      'contamination': 'Contamination',
      'advisory': 'Advisory',
      'view_all': 'View All',
      'predictors_title': 'AI Field Predictors',
      'crop_recommendation': 'Crop Suitability',
      'fertilizer_optimizer': 'Fertilizer Optimizer',
      'yield_predictor': 'Yield & Profit Gain',
      'optimal': 'Optimal',
      'caution': 'Caution',
      'normal': 'Normal',
      'high': 'High',
      'low': 'Low',
      'loading': 'Loading…',
      'fetching_live': 'Fetching live data…',
      'pull_to_refresh': 'Pull down to refresh',
      'retry': 'Retry',
      'error_generic': 'Something went wrong.',
      'error_timeout': 'The request timed out. Check your connection.',
      'error_network': 'No internet connection. Showing saved data.',
      'live_badge': 'LIVE',
      'offline_badge': 'OFFLINE (cached)',
      'updated_just_now': 'Updated just now',
      'grounded_badge': 'Grounded on your farm docs',
      'language_changed': 'Language updated',
      'Wheat': 'Wheat',
      'Rice': 'Rice',
      'Maize': 'Maize',
      'Soybean': 'Soybean',
      'Cotton': 'Cotton',
      'Mustard': 'Mustard',
      'Potato': 'Potato',
      'Onion': 'Onion',
      'Sugarcane': 'Sugarcane',
    },
    'hi': {
      'app_name': 'कृषि मित्र',
      'greeting': 'नमस्ते! 🌱',
      'greeting_sub': 'आज आपका खेत कैसा है?',
      'temp_label': 'तापमान',
      'moisture_label': 'नमी',
      'crop_label': 'मुख्य फसल',
      'voice_module': 'आवाज़ सहायक',
      'sensor_module': 'सेंसर डैशबोर्ड',
      'market_module': 'बाज़ार मूल्य',
      'weather_module': 'मौसम पूर्वानुमान',
      'alerts_module': 'अलर्ट और चेतावनी',
      'recent_alerts': 'नवीनतम अलर्ट',
      'rain_warning_title': 'बारिश की चेतावनी',
      'rain_warning_desc': 'अगले 3 घंटे में बारिश की संभावना',
      'wheat_sell_title': 'गेहूं बेचने का समय',
      'wheat_sell_desc': 'कीमत अभी ऊँची है',
      'market_title': 'बाज़ार मूल्य (मंडी भाव)',
      'weather_title': 'मौसम पूर्वानुमान',
      'sensor_title': 'खेत सेंसर डैशबोर्ड',
      'alerts_title': 'अलर्ट और चेतावनी',
      'home': 'मुख्य',
      'voice': 'आवाज़',
      'market': 'बाज़ार',
      'weather': 'मौसम',
      'selling_tip': 'बेचने का सुझाव',
      'forecast': 'मूल्य पूर्वानुमान',
      'nearby_mandis': 'आस-पास के मंडी भाव',
      'trend': 'मूल्य रुझान',
      'daily_outlook': '7-दिवसीय पूर्वानुमान',
      'nowcast_advisory': 'नाउकास्ट व रडार चेतावनी',
      'season_advice': 'मौसमी कृषि सलाह',
      'recommended_crops': 'अनुशंसित फसलें',
      'humidity_label': 'आर्द्रता',
      'wind_label': 'हवा की गति',
      'rain_label': 'बारिश की संभावना',
      'sensor_connected': 'ESP32 कनेक्टेड - यूनिट #1',
      'sensor_disconnected': 'ESP32 डिस्कनेक्टेड',
      'soil_moisture': 'मिट्टी की नमी',
      'soil_ph': 'मिट्टी का pH',
      'npk_levels': 'NPK पोषक तत्व स्तर',
      'nitrogen': 'नाइट्रोजन (N)',
      'phosphorus': 'फास्फोरस (P)',
      'potassium': 'पोटैशियम (K)',
      'moisture_trend': '24-घंटे का नमी रुझान',
      'smart_alerts_active': 'स्मार्ट अलर्ट सक्रिय',
      'smart_alerts_sub': '24/7 निगरानी: ESP32 + IMD रडार + CPCB जल गुणवत्ता',
      'suggested_action': 'सुझाई गई कार्रवाई',
      'got_it': 'समझ गया',
      'hear': 'ऑडियो सुनें',
      'sensors': 'सेंसर',
      'nowcast': 'नाउकास्ट',
      'contamination': 'प्रदूषण चेतावनी',
      'advisory': 'कृषि सलाह',
      'view_all': 'सभी देखें',
      'predictors_title': 'एआई प्रिडिक्टर इंजन',
      'crop_recommendation': 'फसल उपयुक्तता',
      'fertilizer_optimizer': 'उर्वरक अनुकूलक',
      'yield_predictor': 'उपज व लाभ अनुमान',
      'optimal': 'उत्तम',
      'caution': 'सावधानी',
      'normal': 'सामान्य',
      'high': 'उच्च',
      'low': 'निम्न',
      'loading': 'लोड हो रहा है…',
      'fetching_live': 'लाइव डेटा प्राप्त हो रहा है…',
      'pull_to_refresh': 'ताज़ा करने के लिए नीचे खींचें',
      'retry': 'पुनः प्रयास करें',
      'error_generic': 'कुछ गड़बड़ हो गई।',
      'error_timeout': 'अनुरोध समय समाप्त। कृपया कनेक्शन जांचें।',
      'error_network': 'इंटरनेट कनेक्शन नहीं है। सहेजा गया डेटा दिखा रहे हैं।',
      'live_badge': 'लाइव',
      'offline_badge': 'ऑफ़लाइन (सहेजा गया)',
      'updated_just_now': 'अभी अपडेट किया गया',
      'grounded_badge': 'आपके खेत दस्तावेज़ों पर आधारित',
      'language_changed': 'भाषा अपडेट की गई',
      'Wheat': 'गेहूं',
      'Rice': 'चावल (धान)',
      'Maize': 'मक्का',
      'Soybean': 'सोयाबीन',
      'Cotton': 'कपास',
      'Mustard': 'सरसों',
      'Potato': 'आलू',
      'Onion': 'प्याज',
      'Sugarcane': 'गन्ना',
    },
    'mr': {
      'app_name': 'कृषी मित्र',
      'greeting': 'नमस्कार! 🌱',
      'greeting_sub': 'आज तुमचे शेत कसे आहे?',
      'temp_label': 'तापमान',
      'moisture_label': 'ओलावा',
      'crop_label': 'मुख्य पीक',
      'voice_module': 'आवाज सहाय्यक',
      'sensor_module': 'सेंसर डॅशबोर्ड',
      'market_module': 'बाजार भाव',
      'weather_module': 'हवामान अंदाज',
      'alerts_module': 'सूचना व चेतावणी',
      'recent_alerts': 'नवीनतम सूचना',
      'rain_warning_title': 'पावसाचा इशारा',
      'rain_warning_desc': 'पुढील ३ तासांत पावसाची शक्यता',
      'wheat_sell_title': 'गहू विक्रीची वेळ',
      'wheat_sell_desc': 'सध्याचे भाव चढे आहेत',
      'market_title': 'बाजार भाव (मंडी)',
      'weather_title': 'हवामान अंदाज',
      'sensor_title': 'शेत सेन्सर डॅशबोर्ड',
      'alerts_title': 'सूचना व चेतावणी',
      'home': 'मुख्य',
      'voice': 'आवाज',
      'market': 'बाजार',
      'weather': 'हवामान',
      'selling_tip': 'विक्री सल्ला',
      'forecast': 'भाव अंदाज',
      'nearby_mandis': 'जवळपासचे बाजार भाव',
      'trend': 'भाव कल',
      'daily_outlook': '७-दिवसीय अंदाज',
      'nowcast_advisory': 'नाऊकास्ट व रडार इशारा',
      'season_advice': 'हंगामी कृषी सल्ला',
      'recommended_crops': 'शिफारस केलेली पिके',
      'humidity_label': 'आर्द्रता',
      'wind_label': 'वाऱ्याचा वेग',
      'rain_label': 'पावसाची शक्यता',
      'sensor_connected': 'ESP32 कनेक्टेड - युनिट #१',
      'sensor_disconnected': 'ESP32 डिस्कनेक्टेड',
      'soil_moisture': 'मातीचा ओलावा',
      'soil_ph': 'मातीचा सामू (pH)',
      'npk_levels': 'NPK पोषण पातळी',
      'nitrogen': 'नायट्रोजन (N)',
      'phosphorus': 'फॉस्फरस (P)',
      'potassium': 'पोटॅश (K)',
      'moisture_trend': '२४-तास ओलावा कल',
      'smart_alerts_active': 'स्मार्ट सूचना सक्रिय',
      'smart_alerts_sub': '२४/७ देखरेख: ESP32 + IMD रडार + CPCB पाणी गुणवत्ता',
      'suggested_action': 'सुचवलेली कृती',
      'got_it': 'समजले',
      'hear': 'ऐका',
      'sensors': 'सेंसर',
      'nowcast': 'नाऊकास्ट',
      'contamination': 'प्रदूषण इशारा',
      'advisory': 'सल्ला',
      'view_all': 'सर्व पहा',
      'predictors_title': 'एआय अंदाज इंजिन',
      'crop_recommendation': 'पीक योग्यता',
      'fertilizer_optimizer': 'खत नियोजन',
      'yield_predictor': 'उत्पादन व नफा अंदाज',
      'optimal': 'उत्कृष्ट',
      'caution': 'सावधान',
      'normal': 'सामान्य',
      'high': 'जास्त',
      'low': 'कमी',
      'loading': 'लोड होत आहे…',
      'fetching_live': 'थेट डेटा मिळवत आहे…',
      'pull_to_refresh': 'ताजे करण्यासाठी खाली ओढा',
      'retry': 'पुन्हा प्रयत्न करा',
      'error_generic': 'काहीतरी चूक झाली.',
      'error_timeout': 'वेळ संपली. कृपया इंटरनेट तपासा.',
      'error_network': 'इंटरनेट नाही. साठवलेला डेटा दाखवत आहे.',
      'live_badge': 'थेट (LIVE)',
      'offline_badge': 'ऑफलाइन (कॅश)',
      'updated_just_now': 'आत्ताच अद्यतनित',
      'grounded_badge': 'तुमच्या शेत दस्तऐवजांवर आधारित',
      'language_changed': 'भाषा बदलली गेली',
      'Wheat': 'गहू',
      'Rice': 'भात',
      'Maize': 'मका',
      'Soybean': 'सोयाबीन',
      'Cotton': 'कापूस',
      'Mustard': 'मोहरी',
      'Potato': 'बटाटा',
      'Onion': 'कांदा',
      'Sugarcane': 'ऊस',
    },
    'bn': {
      'app_name': 'কৃষি মিত্র',
      'greeting': 'নমস্কার! 🌱',
      'greeting_sub': 'আজ আপনার খামার কেমন আছে?',
      'temp_label': 'তাপমাত্রা',
      'moisture_label': 'আর্দ্রতা',
      'crop_label': 'প্রধান ফসল',
      'voice_module': 'ভয়েস সহকারী',
      'sensor_module': 'সেন্সর ড্যাশবোর্ড',
      'market_module': 'বাজার দর',
      'weather_module': 'আবহাওয়া',
      'alerts_module': 'সতর্কতা',
      'recent_alerts': 'সাম্প্রতিক সতর্কতা',
      'market_title': 'বাজারের দাম (মান্ডি)',
      'weather_title': 'আবহাওয়ার পূর্বাভাস',
      'sensor_title': 'খামার সেন্সর',
      'alerts_title': 'সতর্কতা ও পূর্বাভাস',
      'home': 'হোম',
      'voice': 'ভয়েস',
      'market': 'বাজার',
      'weather': 'আবহাওয়া',
      'selling_tip': 'বিক্রয় পরামর্শ',
      'forecast': 'দামের পূর্বাভাস',
      'nearby_mandis': 'কাছের বাজারের দর',
      'trend': 'দামের গতিপ্রকৃতি',
      'nowcast': 'নাওকাস্ট',
      'contamination': 'দূষণ সতর্কতা',
      'advisory': 'পরামর্শ',
      'view_all': 'সব দেখুন',
      'optimal': 'অনুকূল',
      'caution': 'সতর্কতা',
      'normal': 'স্বাভাবিক',
      'pull_to_refresh': 'রিফ্রেশ করতে টানুন',
      'live_badge': 'লাইভ',
      'offline_badge': 'অফলাইন',
      'Wheat': 'গম',
      'Rice': 'ধান / চাল',
      'Maize': 'ভুট্টা',
      'Soybean': 'সয়াবিন',
      'Cotton': 'তুলা',
      'Mustard': 'সরিষা',
      'Potato': 'আলু',
      'Onion': 'পেঁয়াজ',
      'Sugarcane': 'আখ',
    },
    'te': {
      'app_name': 'కృషి మిత్ర',
      'greeting': 'నమస్కారం! 🌱',
      'greeting_sub': 'ఈరోజు మీ పొలం ఎలా ఉంది?',
      'temp_label': 'ఉష్ణోగ్రత',
      'moisture_label': 'తేమ',
      'crop_label': 'ప్రధాన పంట',
      'voice_module': 'వాయిస్ అసిస్టెంట్',
      'sensor_module': 'సెన్సార్ డాష్బోర్డ్',
      'market_module': 'మార్కెట్ ధరలు',
      'weather_module': 'వాతావరణం',
      'alerts_module': 'హెచ్చరికలు',
      'recent_alerts': 'ఇటీవలి హెచ్చరికలు',
      'market_title': 'మార్కెట్ ధరలు (మండి)',
      'weather_title': 'వాతావరణ సమాచారం',
      'sensor_title': 'పొలం సెన్సార్లు',
      'alerts_title': 'హెచ్చరికలు',
      'home': 'హోమ్',
      'voice': 'వాయిస్',
      'market': 'మార్కెట్',
      'weather': 'వాతావరణం',
      'selling_tip': 'అమ్మకపు సలహా',
      'forecast': 'ధరల అంచనా',
      'nearby_mandis': 'సమీప మార్కెట్ ధరలు',
      'trend': 'ధరల సరళి',
      'nowcast': 'నౌకాస్ట్',
      'contamination': 'కాలుష్య హెచ్చరిక',
      'advisory': 'సలహా',
      'view_all': 'అన్నీ చూడండి',
      'optimal': 'అనుకూలం',
      'caution': 'హెచ్చరిక',
      'normal': 'సాధారణం',
      'pull_to_refresh': 'రిఫ్రెష్ చేయడానికి లాగండి',
      'live_badge': 'లైవ్',
      'offline_badge': 'ఆఫ్లైన్',
      'Wheat': 'గోధుమలు',
      'Rice': 'వరి / బియ్యం',
      'Maize': 'మొక్కజొన్న',
      'Soybean': 'సోయాబీన్',
      'Cotton': 'పత్తి',
      'Mustard': 'ఆవాలు',
      'Potato': 'బంగాళాదుంప',
      'Onion': 'ఉల్లిపాయ',
      'Sugarcane': 'చెరకు',
    },
    'ta': {
      'app_name': 'கிஷி மித்ரா',
      'greeting': 'வணக்கம்! 🌱',
      'greeting_sub': 'இன்று உங்கள் பண்ணை எப்படி உள்ளது?',
      'temp_label': 'வெப்பநிலை',
      'moisture_label': 'ஈரப்பதம்',
      'crop_label': 'முக்கிய பயிர்',
      'voice_module': 'குரல் உதவியாளர்',
      'sensor_module': 'சென்சார் பலகை',
      'market_module': 'சந்தை விலை',
      'weather_module': 'வானிலை',
      'alerts_module': 'எச்சரிக்கைகள்',
      'recent_alerts': 'சமீபத்திய எச்சரிக்கைகள்',
      'market_title': 'சந்தை விலைகள்',
      'weather_title': 'வானிலை அறிக்கை',
      'sensor_title': 'பண்ணை சென்சார்கள்',
      'alerts_title': 'எச்சரிக்கைகள்',
      'home': 'முகப்பு',
      'voice': 'குரல்',
      'market': 'சந்தை',
      'weather': 'வானிலை',
      'selling_tip': 'விற்பனை குறிப்பு',
      'forecast': 'விலை கணிப்பு',
      'nearby_mandis': 'அருகிலுள்ள சந்தை விலைகள்',
      'trend': 'விலை போக்கு',
      'nowcast': 'நவ்காஸ்ட்',
      'contamination': 'மாசு எச்சரிக்கை',
      'advisory': 'ஆலோசனை',
      'view_all': 'அனைத்தும் பார்க்க',
      'optimal': 'சிறந்தது',
      'caution': 'கவனம்',
      'normal': 'இயல்பு',
      'pull_to_refresh': 'புதுப்பிக்க கீழே இழுக்கவும்',
      'live_badge': 'லைவ்',
      'offline_badge': 'ஆஃப்லைன்',
      'Wheat': 'கோதுமை',
      'Rice': 'நெல் / அரிசி',
      'Maize': 'சோளம்',
      'Soybean': 'சோயாபீன்',
      'Cotton': 'பருத்தி',
      'Mustard': 'கடுகு',
      'Potato': 'உருளைக்கிழங்கு',
      'Onion': 'வெங்காயம்',
      'Sugarcane': 'கரும்பு',
    },
    'gu': {
      'app_name': 'કૃષિ મિત્ર',
      'greeting': 'નમસ્તે! 🌱',
      'greeting_sub': 'આજે તમારું ખેતર કેવું છે?',
      'temp_label': 'તાપમાન',
      'moisture_label': 'ભેજ',
      'crop_label': 'મુખ્ય પાક',
      'voice_module': 'અવાજ સહાયક',
      'sensor_module': 'સેન્સર ડેશબોર્ડ',
      'market_module': 'બજાર ભાવ',
      'weather_module': 'હવામાન',
      'alerts_module': 'ચેતવણીઓ',
      'recent_alerts': 'તાજેતરની ચેતવણીઓ',
      'market_title': 'મંડી ભાવો',
      'weather_title': 'હવામાન આગાહી',
      'sensor_title': 'ખેતર સેન્સર',
      'alerts_title': 'ચેતવણીઓ',
      'home': 'હોમ',
      'voice': 'અવાજ',
      'market': 'બજાર',
      'weather': 'હવામાન',
      'nowcast': 'નાવકાસ્ટ',
      'contamination': 'પ્રદૂષણ ચેતવણી',
      'advisory': 'સલાહ',
      'view_all': 'બધું જુઓ',
      'optimal': 'શ્રેષ્ઠ',
      'caution': 'સાવધાની',
      'normal': 'સામાન્ય',
      'pull_to_refresh': 'રિફ્રેશ કરવા નીચે ખેંચો',
      'live_badge': 'લાઇવ',
      'offline_badge': 'ઑફલાઇન',
      'Wheat': 'ઘઉં',
      'Rice': 'ડાંગર / ચોખા',
      'Maize': 'મકાઈ',
      'Soybean': 'સોયાબીન',
      'Cotton': 'કપાસ',
      'Mustard': 'સરસવ',
      'Potato': 'બટાટા',
      'Onion': 'ડુંગળી',
      'Sugarcane': 'શેરડી',
    },
    'kn': {
      'app_name': 'ಕೃಷಿ ಮಿತ್ರ',
      'greeting': 'ನಮಸ್ಕಾರ! 🌱',
      'greeting_sub': 'ಇಂದು ನಿಮ್ಮ ಜಮೀನು ಹೇಗಿದೆ?',
      'temp_label': 'ತಾಪಮಾನ',
      'moisture_label': 'ತೇವಾಂಶ',
      'crop_label': 'ಮುಖ್ಯ ಬೆಳೆ',
      'voice_module': 'ಧ್ವನಿ ಸಹಾಯಕ',
      'sensor_module': 'ಸೆನ್ಸಾರ್ ಡ್ಯಾಶ್ಬೋರ್ಡ್',
      'market_module': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
      'weather_module': 'ಹವಾಮಾನ',
      'alerts_module': 'ಎಚ್ಚರಿಕೆಗಳು',
      'recent_alerts': 'ಇತ್ತೀಚಿನ ಎಚ್ಚರಿಕೆಗಳು',
      'market_title': 'ಮಾರುಕಟ್ಟೆ ದರಗಳು',
      'weather_title': 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
      'sensor_title': 'ಕ್ಷೇತ್ರ ಸೆನ್ಸಾರ್',
      'alerts_title': 'ಎಚ್ಚರಿಕೆಗಳು',
      'home': 'ಮುಖಪುಟ',
      'voice': 'ಧ್ವನಿ',
      'market': 'ಮಾರುಕಟ್ಟೆ',
      'weather': 'ಹವಾಮಾನ',
      'nowcast': 'ನೌಕಾಸ್ಟ್',
      'contamination': 'ಮಾಲಿನ್ಯ ಎಚ್ಚರಿಕೆ',
      'advisory': 'ಸಲಹೆ',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ವೀಕ್ಷಿಸಿ',
      'optimal': 'ಉತ್ತಮ',
      'caution': 'ಎಚ್ಚರಿಕೆ',
      'normal': 'ಸಾಮಾನ್ಯ',
      'pull_to_refresh': 'ರಿಫ್ರೆಶ್ ಮಾಡಲು ಎಳೆಯಿರಿ',
      'live_badge': 'ಲೈವ್',
      'offline_badge': 'ಆಫ್ಲೈನ್',
      'Wheat': 'ಗೋಧಿ',
      'Rice': 'ಭತ್ತ / ಅಕ್ಕಿ',
      'Maize': 'ಮೆಕ್ಕೆಜೋಳ',
      'Soybean': 'ಸೋಯಾಬೀನ್',
      'Cotton': 'ಹತ್ತಿ',
      'Mustard': 'ಸಾಸಿವೆ',
      'Potato': 'ಆಲೂಗಡ್ಡೆ',
      'Onion': 'ಈರುಳ್ಳಿ',
      'Sugarcane': 'ಕಬ್ಬು',
    },
    'ml': {
      'app_name': 'കൃഷി മിത്ര',
      'greeting': 'നമസ്കാരം! 🌱',
      'greeting_sub': 'ഇന്ന് നിങ്ങളുടെ കൃഷിസ്ഥലം എങ്ങനെയുണ്ട്?',
      'temp_label': 'താപനില',
      'moisture_label': 'ഈർപ്പം',
      'crop_label': 'പ്രധാന വിള',
      'voice_module': 'വോയ്സ് അസിസ്റ്റന്റ്',
      'sensor_module': 'സെൻസർ ഡാഷ്ബോർഡ്',
      'market_module': 'വിപണി വില',
      'weather_module': 'കാലാവസ്ഥ',
      'alerts_module': 'മുന്നറിയിപ്പുകൾ',
      'recent_alerts': 'പുതിയ മുന്നറിയിപ്പുകൾ',
      'market_title': 'വിപണി നിരക്കുകൾ',
      'weather_title': 'കാലാവസ്ഥ പ്രവചനം',
      'sensor_title': 'വയൽ സെൻസറുകൾ',
      'alerts_title': 'മുന്നറിയിപ്പുകൾ',
      'home': 'ഹോം',
      'voice': 'ശബ്ദം',
      'market': 'വിപണി',
      'weather': 'കാലാവസ്ഥ',
      'nowcast': 'നൗകാസ്റ്റ്',
      'contamination': 'മലിനീകരണ മുന്നറിയിപ്പ്',
      'advisory': 'ഉപദേശം',
      'view_all': 'എല്ലാം കാണുക',
      'optimal': 'അനുയോജ്യം',
      'caution': 'ജാഗ്രത',
      'normal': 'സാധാരണം',
      'pull_to_refresh': 'പുതുക്കാൻ താഴേക്ക് വലിക്കുക',
      'live_badge': 'ലൈവ്',
      'offline_badge': 'ഓഫ്ലൈൻ',
      'Wheat': 'ഗോതമ്പ്',
      'Rice': 'നെല്ല് / അരി',
      'Maize': 'ചോളം',
      'Soybean': 'സോയാബീൻ',
      'Cotton': 'പരുത്തി',
      'Mustard': 'കടുക്',
      'Potato': 'ഉരുളക്കിഴങ്ങ്',
      'Onion': 'സവാള',
      'Sugarcane': 'കരിമ്പ്',
    },
    'pa': {
      'app_name': 'ਕ੍ਰਿਸ਼ੀ ਮਿੱਤਰ',
      'greeting': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! 🌱',
      'greeting_sub': 'ਅੱਜ ਤੁਹਾਡਾ ਖੇਤ ਕਿਵੇਂ ਹੈ?',
      'temp_label': 'ਤਾਪਮਾਨ',
      'moisture_label': 'ਨਮੀ',
      'crop_label': 'ਮੁੱਖ ਫ਼ਸਲ',
      'voice_module': 'ਆਵਾਜ਼ ਸਹਾਇਕ',
      'sensor_module': 'ਸੈਂਸਰ ਡੈਸ਼ਬੋਰਡ',
      'market_module': 'ਮੰਡੀ ਭਾਅ',
      'weather_module': 'ਮੌਸਮ',
      'alerts_module': 'ਚੇਤਾਵਨੀਆਂ',
      'recent_alerts': 'ਤਾਜ਼ਾ ਚੇਤਾਵਨੀਆਂ',
      'market_title': 'ਮੰਡੀ ਦੇ ਭਾਅ',
      'weather_title': 'ਮੌਸਮ ਦੀ ਭਵਿੱਖਬਾਣੀ',
      'sensor_title': 'ਖੇਤ ਸੈਂਸਰ',
      'alerts_title': 'ਚੇਤਾਵਨੀਆਂ',
      'home': 'ਮੁੱਖ',
      'voice': 'ਆਵਾਜ਼',
      'market': 'ਮੰਡੀ',
      'weather': 'ਮੌਸਮ',
      'nowcast': 'ਨੌਕਾਸਟ',
      'contamination': 'ਪ੍ਰਦੂਸ਼ਣ ਚੇਤਾਵਨੀ',
      'advisory': 'ਸਲਾਹ',
      'view_all': 'ਸਭ ਦੇਖੋ',
      'optimal': 'ਵਧੀਆ',
      'caution': 'ਸਾਵਧਾਨੀ',
      'normal': 'ਆਮ',
      'pull_to_refresh': 'ਤਾਜ਼ਾ ਕਰਨ ਲਈ ਹੇਠਾਂ ਖਿੱਚੋ',
      'live_badge': 'ਲਾਈਵ',
      'offline_badge': 'ਔਫਲਾਈਨ',
      'Wheat': 'ਕਣਕ',
      'Rice': 'ਝੋਨਾ / ਚੌਲ',
      'Maize': 'ਮੱਕੀ',
      'Soybean': 'ਸੋਇਆਬੀਨ',
      'Cotton': 'ਕਪਾਹ',
      'Mustard': 'ਸਰ੍ਹੋਂ',
      'Potato': 'ਆਲੂ',
      'Onion': 'ਪਿਆਜ਼',
      'Sugarcane': 'ਗੰਨਾ',
    },
  };
}
